version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petgomania-api
    ports:
      - "5001:80" # Expose API on port 5001
    env_file:
      - .env # Load environment variables from the .env file
    restart: always
    networks:
      - app-network # Use a network to connect with other services

networks:
  app-network:
    driver: bridge
