version: "3.8"

services:
  server:
    build: .
    container_name: petgomania-api
    ports:
      - "5001:5001" # Expose API on port 5001
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
