version: '3.8'
services:
  api:
    build: .
    container_name: petgomania-api
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: yarn start
