version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petgomania-api
    network_mode: host
    # ports:
    #   - "5001:5001" # Expose API on port 5001
    env_file:
      - .env # Load environment variables from the .env file
    restart: always
    # networks:
    #   - app-network 

    # networks:
    #   app-network:
    #     driver: bridge
